graph LR
    subgraph Docker Bridge Network [app-network]
        Front[tienda_frontend<br/>80:8080]
        Ventas[tienda_backend_ventas<br/>8080:8080]
        Despachos[tienda_backend_despachos<br/>8081:8081]
        DB[(tienda_db<br/>3306:3306)]
        
        Front -- "Proxy Pass (/api/ventas/*)" --> Ventas
        Front -- "Proxy Pass (/api/despachos/*)" --> Despachos
        Ventas -- "MySQL Driver" --> DB
        Despachos -- "MySQL Driver" --> DB
    end
    
    style Front fill:#D4E6F1,stroke:#2874A6
    style Ventas fill:#D5F5E3,stroke:#239B56
    style Despachos fill:#D5F5E3,stroke:#239B56
    style DB fill:#FCF3CF,stroke:#B7950B
