stateDiagram-v2
    [*] --> GitPush: Developer pushes to 'deploy'
    GitPush --> ActionTriggered: GitHub Actions
    
    state ActionTriggered {
        [*] --> Checkout
        Checkout --> LoginAWS
        LoginAWS --> BuildDocker
        BuildDocker --> PushECR
        PushECR --> DeploySSM
        DeploySSM --> [*]
    }
    
    ActionTriggered --> EC2_State: aws ssm
    
    state EC2_State {
        [*] --> GitPull
        GitPull --> DockerLogin
        DockerLogin --> ExportEnvVars
        ExportEnvVars --> ComposePull
        ComposePull --> ComposeUp
        ComposeUp --> [*]
    }
    
    EC2_State --> Success
    Success --> [*]
