name: CI/CD Tienda Perritos - Frontend

on:
  push:
    branches: [ "deploy" ]
    paths:
      - "frontend/**"
      - ".github/workflows/cicd-tienda-frontend.yml"

jobs:
  build-push-deploy-frontend:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Configurar credenciales AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Login en Amazon ECR
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build imagen Frontend y push a ECR
      run: |
        cd frontend
        docker build -t tienda-frontend .
        docker tag tienda-frontend:latest ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest
        docker push ${{ secrets.ECR_REPO_URL_FRONTEND }}:latest

    - name: Desplegar Frontend vía SSM (Docker Compose)
      run: |
        aws ssm send-command \
          --instance-ids ${{ secrets.EC2_FRONTEND_INSTANCE_ID }} \
          --document-name "AWS-RunShellScript" \
          --comment "Actualizar tienda-frontend desde ECR" \
          --parameters '{"commands":[
            "set -e",
            "mkdir -p /home/ubuntu/app",
            "cd /home/ubuntu/app",
            "curl -H 'Cache-Control: no-cache, no-store' -o docker-compose.yml https://raw.githubusercontent.com/jeffplop/test_aws_grav/deploy/docker-compose.yml",
            "aws ecr get-login-password --region '${{ secrets.AWS_REGION }}' | docker login --username AWS --password-stdin ${{ secrets.ECR_REGISTRY }}",
            "export FRONTEND_IMAGE=${{ secrets.ECR_REPO_URL_FRONTEND }}:latest",
            "docker compose pull frontend",
            "docker compose up -d frontend"
          ]}' \
          --output text
